checkpoint_dir: ./checkpoints
checkpoint_file: U-Net++-v8.ckpt
project_name: U-Net++

#----------------------------------#
run_name: resnet152_300epoch

seed: 42

batch_size: 8
num_workers: 8

lr: 1e-4

input_size: 2048
max_epoch: 100
valid_interval: 5

amp: True