checkpoint_dir: ./checkpoints
checkpoint_file: U_Net_pp.pt
project_name: U-Net++

#----------------------------------#
run_name: resnet34(default)

seed: 42

batch_size: 20
num_workers: 8

lr: 1e-4

input_size: 512
max_epoch: 50
valid_interval: 1

amp: True