checkpoint_dir: ./checkpoints
checkpoint_file: UPerNet_Eff7_best_model.pt
project_name: Crop_image

#----------------------------------#
run_name: Palm image with CLAHE

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7
encoder_weight: imagenet

seed: 42

batch_size: 4
num_workers: 4

lr: 1e-3

input_size: 1024
max_epoch: 100
valid_interval: 10

amp: True