checkpoint_dir: ./checkpoints
checkpoint_file: UPerNet_Eff7_cropped-bestEp_98
resume_checkpoint_suffix: -latest  # Resume 전용 체크포인트 접미사: -latest, -bestEp_00, None, ...
project_name: Last_Dance_palm

#----------------------------------#
run_name: Palm

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7
encoder_weight: imagenet

seed: 42

batch_size: 2
num_workers: 4

lr: 1e-3

input_size: 1024
max_epoch: 100
valid_interval: 100
  
amp: False

use_cp: True
cp_args:
 - Trapezium
 - Capitate
 - Lunate 
 - Scaphoid 
 - finger-1 
 - finger-16 
 - Pisiform 
 - Hamate 
 - Triquetrum
