checkpoint_dir: ./checkpoints
checkpoint_file: fcn_resnet50_best_model.pt
project_name: project4_test_run

#----------------------------------#
run_name: test yaml

architecture: Unet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b0
encoder_weight: imagenet

seed: 42

batch_size: 1
num_workers: 8

lr: 1e-4

input_size: 512
max_epoch: 10
valid_interval: 5

amp: True