checkpoint_dir: ./checkpoints
checkpoint_file: Model_Encoder_Best
resume_checkpoint_suffix: -latest  # Resume 전용 체크포인트 접미사: -latest, -bestEp_00, None, ...
project_name: Last_Dance

#----------------------------------#
run_name: custom_scheduler

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7
encoder_weight: imagenet

seed: 42

batch_size: 2
num_workers: 4

lr: 1e-3

input_size: 1024
max_epoch: 100
valid_interval: 100
  
amp: False