checkpoint_dir: ./checkpoints
checkpoint_file: fcn_resnet50_best_model.pt
resume_checkpoint_suffix: -latest  # Resume 전용 체크포인트 접미사: -latest, -bestEp_00, None, ...
project_name: project4_test_run

#----------------------------------#
run_name: test yaml

architecture: Unet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b0
encoder_weight: imagenet

seed: 42

batch_size: 20
num_workers: 8

lr: 1e-4

input_size: 512
max_epoch: 5
valid_interval: 5

amp: True