checkpoint_dir: ./checkpoints/pspnet/resnet152/1024
checkpoint_file: pspnet_resnet152_1024_best_model
project_name: PSPNet

#----------------------------------#
run_name: resnet152_16bs_1024_100ep

architecture: PSPNet               # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: resnet152
encoder_weight: imagenet

seed: 42

batch_size: 16
num_workers: 8

lr: 1e-4

input_size: 1024
max_epoch: 101
valid_interval: 5

amp: True
