checkpoint_dir: ./checkpoints
checkpoint_file: fcn_resnet50_best_model.pt
project_name: project4_test_run

#----------------------------------#
run_name: aug_test

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7
encoder_weight: imagenet

seed: 42

batch_size: 4
num_workers: 4

lr: 1e-3

input_size: 1024
max_epoch: 30
valid_interval: 5
clahe: true
clahe_clip_limit: 4.0
clahe_tile_grid_size: [4, 4]

amp: True