checkpoint_dir: ./checkpoints
checkpoint_file: UPerNet_Eff7_cropped-bestEp_98
project_name: Crop_image

#----------------------------------#
run_name: crop_img

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7
encoder_weight: imagenet

seed: 42

batch_size: 4
num_workers: 4

lr: 1e-4

input_size: 1024
max_epoch: 2
valid_interval: 5
clahe: true
clahe_clip_limit: 2.0
clahe_tile_grid_size: [8, 8]
valid: True


amp: True

standard_csv_path: standard_output.csv