checkpoint_dir: ./checkpoints/UPerNet/efficient/
checkpoint_file: test
project_name: Aug_test

#----------------------------------#
run_name: test

architecture: UperNet                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b7        # timm 라이브러리 사용하려면 encoder 이름에 tu- 붙여서 사용 ex) tu-hrnet_w64
encoder_weight: imagenet

seed: 42

batch_size: 4
num_workers: 8

lr: 1e-3

input_size: 512
max_epoch: 30
valid_interval: 5

amp: True
