# 크롭 정보
crop_info_path: ./tools/crop_info.json

# Palm 모델에서 사용할 GT CSV 경로
#palm_gt_csv: "./tools/gt.csv"

# 이미지를 포함한 루트 폴더 경로
image_root: /data/ephemeral/home/data/test/DCM

# 결과를 저장할 폴더 경로
save_dir: ./soft_ensemble

# 저장할 결과 파일 이름
output_name: output_class_test_1.csv

# save = Palm 모델과 일반 모델의 출력을 결합하여 .npz 파일로 저장
# load = 저장된 결합 결과를 로드하여 새로운 Threshold를 적용
# save_load = save하고 자동으로 load까지 실행함
prediction_save: True
mode: "save_load"  # "save", "load", "save_load"
prediction_file: "predictions"  # 저장 및 로드할 예측 파일 이름

# 배치 크기 / 데이터로더의 워커 수
batch_size: 2
num_workers: 2

# 결합 비율(합계가 1이 되도록 설정)
palm_weight: 0.6
smp_weight: 0.4


smp_model_paths:
  - "./checkpoint/pt/pspnet_save_test_2-all.pt"
#  - "./checkpoint/pt/SAM2Unet_save-all_1.pt"
#  - "./checkpoint/pt/SAM2Unet_save-all_2.pt"


palm_model_paths:
  - "./checkpoint/pt/SAM2Unet_palm-final.pt"


#mmseg_model_paths:
#  - "path"

# 예측값을 이진화할 임계값
class_thresholds:
  - 0.5  # finger-1
  - 0.5  # finger-2
  - 0.5  # finger-3
  - 0.5  # finger-4
  - 0.5  # finger-5
  - 0.5  # finger-6
  - 0.5  # finger-7
  - 0.5  # finger-8
  - 0.5  # finger-9
  - 0.5  # finger-10
  - 0.5  # finger-11
  - 0.5  # finger-12
  - 0.5  # finger-13
  - 0.5  # finger-14
  - 0.5  # finger-15
  - 0.6  # finger-16
  - 0.5  # finger-17
  - 0.5  # finger-18
  - 0.5  # finger-19
  - 0.6  # Trapezium
  - 0.6  # Trapezoid
  - 0.6  # Capitate
  - 0.6  # Hamate
  - 0.6  # Scaphoid
  - 0.6  # Lunate
  - 0.6  # Triquetrum
  - 0.6  # Pisiform
  - 0.5  # Radius
  - 0.5  # Ulna