checkpoint_dir: /data/ephemeral/home/hobbang/checkpoints/from_CVAT2/train
checkpoint_file: SAM2Unet_test
resume_checkpoint_suffix: -latest  # Resume 전용 체크포인트 접미사: -latest, -bestEp_00, None, ...
project_name: Data Test

#----------------------------------#
run_name: from_CVAT2_train

seed: 42

batch_size: 4
num_workers: 4

learning_rate: 1e-4

max_epoch: 44
input_size: 1024
valid_interval: 5

amp: True
