checkpoint_dir: ./checkpoints/segformer
checkpoint_file: s
project_name: project4_mmseg_test

#----------------------------------#
run_name: upernet_15epochs

seed: 42

batch_size: 3
num_workers: 2

lr: 6e-4

input_size: 512
max_step: 5000
valid_step: 1000

amp: True

resume: True
wandb_id: -1

auto_eval: True
tta: False