checkpoint_dir: ./checkpoints
checkpoint_file: segformer.pth
project_name: last_dance_mmseg

#----------------------------------#
run_name: segformer_b3_20000

seed: 42

batch_size: 2
num_workers: 3

lr: 1.25e-4

input_size: 1024
max_step: 20000
valid_step: 2000

amp: False

resume: False
wandb_id: -1

config: configs_cv13/segformer_b3.py

auto_eval: True
tta: False