checkpoint_dir: ./checkpoints
checkpoint_file: FCN_HRNet.pth
project_name: HRNet

#----------------------------------#
run_name: HRNet

seed: 42

batch_size: 4
num_workers: 4

lr: 6e-4

input_size: 512
max_step: 10000
valid_step: 1000

amp: True

resume: True
wandb_id: -1

auto_eval: True
tta: False