checkpoint_dir: ./checkpoints
checkpoint_file: UPerNet_HRNet.pth
project_name: HRNet

#----------------------------------#
run_name: HRNet_UPerNet

seed: 42

batch_size: 2
num_workers: 2

lr: 6e-4

input_size: 512
max_step: 10000
valid_step: 1000

amp: True

resume: True
wandb_id: -1

auto_eval: True
tta: False