_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 106
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.10.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
amp:
    value: true
batch_size:
    value: 20
checkpoint_dir:
    value: ./checkpoints
checkpoint_file:
    value: fcn_resnet50_best_model.pt
criterion:
    value: null
encoder_name:
    value: efficientnet-b0
encoder_weight:
    value: imagenet
input_size:
    value: 512
learning_rate:
    value: 0.0001
lr:
    value: 0.0001
max_epoch:
    value: 5
num_workers:
    value: 8
seed:
    value: 42
thr:
    value: 0.5
valid_interval:
    value: 1
