checkpoint_dir: ./checkpoints
checkpoint_file: segformer_best_model.pt
project_name: segformer

#----------------------------------#
run_name: test yaml

architecture: Segformer                # "Unet", "UperNet", "DeepLabV3", "DeepLabV3Plus", "PSPNet", "FPN", "Linknet", "Pan", "MAnet"
encoder_name: efficientnet-b0
encoder_weight: imagenet

seed: 42

batch_size: 8
num_workers: 8

lr: 1e-3

input_size: 512
max_epoch: 100
valid_interval: 1

amp: True

