model_name: DeepLabV3Plus
project_name: ExampleProject
run_name: Experiment1
image_root: /data/ephemeral/home/data/train/DCM
label_root: /data/ephemeral/home/data/train/outputs_json
batch_size: 16
num_workers: 4
input_size: 512
max_epoch: 50
valid_interval: 1
checkpoint_dir: ./checkpoints
seed: 42
lr: 0.0001

# Augmentations 설정
augmentations:
  - type: grid_dropout
    params:
      ratio: 0.5
      unit_size_min: 32
      unit_size_max: 64
      p: 0.5
  - type: cutout
    params:
      num_holes: 8
      max_h_size: 32
      max_w_size: 32
      p: 0.5
  - type: mixup
    params:
      alpha: 0.4
  - type: cutmix
    params:
      alpha: 0.4