# 프로젝트 및 실행 정보
project_name: "SemanticSegmentation"
run_name: "Unet++"

# 데이터셋 경로
image_root: "/data/ephemeral/home/data/train/DCM"
label_root: "/data/ephemeral/home/data/train/outputs_json"

# 학습 관련 설정
batch_size: 16
num_workers: 4
input_size: 512
max_epoch: 100
valid_split: 0.2
valid_interval: 1
checkpoint_dir: "./checkpoints"
seed: 42
lr: 0.0001

# 모델 설정
model_name: "Unet++"
encoder_name: "resnet34"
encoder_weights: "imagenet"
classes: 29

# Augmentations 설정
train_transforms:
  - type: "Resize"
    params:
      height: 512
      width: 512
  - type: "HorizontalFlip"
    params:
      p: 0.5
  - type: "RandomBrightnessContrast"
    params:
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5
  - type: "CoarseDropout"
    params:
      max_holes: 8
      max_height: 32
      max_width: 32
      p: 0.5

valid_transforms:
  - type: "Resize"
    params:
      height: 512
      width: 512
