checkpoint_dir: ./checkpoints
checkpoint_file: fcn_resnet50_best_model.pt
project_name: project4_test_run

#----------------------------------#
run_name: test yaml

seed: 42

batch_size: 20
num_workers: 8

lr: 1e-4

input_size: 512
max_epoch: 100
valid_interval: 1

amp: False