image_root: /data/ephemeral/home/data/test/DCM

root_path: /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble

CLASSES: [
    'finger-1', 'finger-2', 'finger-3', 'finger-4', 'finger-5',
    'finger-6', 'finger-7', 'finger-8', 'finger-9', 'finger-10',
    'finger-11', 'finger-12', 'finger-13', 'finger-14', 'finger-15',
    'finger-16', 'finger-17', 'finger-18', 'finger-19', 'Trapezium',
    'Trapezoid', 'Capitate', 'Hamate', 'Scaphoid', 'Lunate',
    'Triquetrum', 'Pisiform', 'Radius', 'Ulna',
]

batch_size: 2
num_workers: 2

threshold: 0.5

model_paths:
  512:
#    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/lightningmodule/tools/Ensemble/test_ckpt/segformer_18000.pth
#    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/test_ckpt/pspnet_mit_b5_best_model_5e-5.ckpt
    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/checkpoint/pt/pspnet_save_test_2-all.pt
    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/checkpoint/pt/SAM2Unet_save-all_1.pt
    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/checkpoint/pt/SAM2Unet_save-all_2.pt
  1024: []
#    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/test_ckpt/SAM2Unet_clahe-bestEp_81.ckpt
#    - /data/ephemeral/home/kjh/level2-cv-semanticsegmentation-cv-13-lv3/ensemble/test_ckpt/SAM2Unet_test-bestEp_81.ckpt
  1536: []
  2048: []

save_dir: ./soft_ensemble
output_name: output5.csv